before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
brews:
  - name: kafkatail
    tap:
      owner: handofgod94
      name: homebrew-kafkatail
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    skip_upload: auto
    commit_author:
      name: Gahan Rakholia
      email: gahan94rakh@gmail.com
    commit_msg_template: 'Brew formula update for {{ .ProjectName }} version {{ .Tag }}'
    homepage: 'https://github.com/HandOfGod94/kafkatail'
    description: 'tail kafka logs from any topic, any wire format on local console'
    license: 'Apache-2.0'
    folder: Formula
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^refactor:'
      - '^build:'
      - '^release:'
      - '^chore:'
      - '^Merge'
