# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: starwars.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("starwars.proto", :syntax => :proto3) do
    add_message "starwars.Character" do
      optional :id, :uint32, 1
      optional :name, :string, 2
      repeated :friends, :message, 3, "starwars.Character"
      repeated :appearsIn, :enum, 4, "starwars.Episode"
      optional :species, :enum, 5, "starwars.Species"
    end
    add_message "starwars.Human" do
      optional :character, :message, 1, "starwars.Character"
      optional :homePlanet, :string, 2
      optional :height, :message, 3, "starwars.Human.Height"
      optional :mass, :float, 4
      repeated :starship, :message, 5, "starwars.Starship"
    end
    add_message "starwars.Human.Height" do
      optional :unit, :enum, 1, "starwars.LengthUnit"
      optional :value, :float, 2
    end
    add_message "starwars.Droid" do
      optional :character, :message, 1, "starwars.Character"
      optional :primaryFunction, :string, 2
    end
    add_message "starwars.FriendsConnection" do
      optional :totalCount, :uint32, 1
      repeated :edges, :message, 2, "starwars.FriendsEdge"
      repeated :friends, :message, 3, "starwars.Character"
      optional :pageinfo, :message, 4, "starwars.PageInfo"
    end
    add_message "starwars.FriendsEdge" do
      optional :cursor, :uint32, 1
      optional :node, :message, 2, "starwars.Character"
    end
    add_message "starwars.PageInfo" do
      optional :startCursor, :uint32, 1
      optional :endCursor, :uint32, 2
      optional :hasNextPage, :bool, 3
    end
    add_message "starwars.Review" do
      optional :episode, :enum, 1, "starwars.Episode"
      optional :stars, :uint32, 2
      optional :commentary, :string, 3
    end
    add_message "starwars.ReviewInput" do
      optional :stars, :uint32, 1
      optional :commentary, :string, 2
      optional :favouriteColour, :message, 3, "starwars.ColourInput"
    end
    add_message "starwars.ColourInput" do
      optional :red, :uint32, 1
      optional :green, :uint32, 2
      optional :blue, :uint32, 3
    end
    add_message "starwars.Starship" do
      optional :id, :uint32, 1
      optional :name, :string, 2
      optional :length, :message, 3, "starwars.Starship.Length"
      repeated :coordinates, :message, 4, "starwars.Starship.Row"
    end
    add_message "starwars.Starship.Length" do
      optional :unit, :enum, 1, "starwars.LengthUnit"
      optional :value, :float, 2
    end
    add_message "starwars.Starship.Row" do
      repeated :values, :float, 1
    end
    add_enum "starwars.Episode" do
      value :NEWHOPE, 0
      value :EMPIRE, 1
      value :JEDI, 2
    end
    add_enum "starwars.Species" do
      value :HUMAN, 0
      value :DROID, 1
    end
    add_enum "starwars.LengthUnit" do
      value :METER, 0
      value :FOOT, 1
    end
  end
end

module Starwars
  Character = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starwars.Character").msgclass
  Human = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starwars.Human").msgclass
  Human::Height = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starwars.Human.Height").msgclass
  Droid = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starwars.Droid").msgclass
  FriendsConnection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starwars.FriendsConnection").msgclass
  FriendsEdge = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starwars.FriendsEdge").msgclass
  PageInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starwars.PageInfo").msgclass
  Review = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starwars.Review").msgclass
  ReviewInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starwars.ReviewInput").msgclass
  ColourInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starwars.ColourInput").msgclass
  Starship = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starwars.Starship").msgclass
  Starship::Length = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starwars.Starship.Length").msgclass
  Starship::Row = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starwars.Starship.Row").msgclass
  Episode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starwars.Episode").enummodule
  Species = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starwars.Species").enummodule
  LengthUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("starwars.LengthUnit").enummodule
end
