name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
        zookeeper:
          image: docker.io/bitnami/zookeeper:3.7
          ports:
            - "2181:2181"
          volumes:
            - "zookeeper_data:/bitnami"
          environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        kafka:
          image: docker.io/bitnami/kafka:2
          ports:
            - "9092:9092"
            - "9093:9093"
          volumes:
            - "kafka_data:/bitnami"
          environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
            - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
            - ALLOW_PLAINTEXT_LISTENER=yes
          depends_on:
            - zookeeper

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Lint
      run: |
        make setup-tools
        make quality-check

    - name: Test
      run: 	go test -timeout 30s -count=1 -race ./...
