name: release

on: workflow_dispatch

env:
  HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
  SCOOP_BUCKET_GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
  SNAPCRAFT_LOGIN: ${{ secrets.SNAPCRAFT_LOGIN }}

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Get latest release tag
        run: echo "RELEASE_VERSION=`echo $(git describe --abbrev=0)`" >> $GITHUB_ENV
      - name: Install snapcraft deps
        run: sudo snap install snapcraft --channel=6.0/stable --classic
      - name: Login to snapcraft
        run: echo ${{ env.SNAPCRAFT_LOGIN }} | snapcraft login --with -
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: v0.183.0
          args: release --rm-dist --release-notes=./changes/${{ env.RELEASE_VERSION }}.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
