// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: testdata/starwars.proto

package testdata

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Episode int32

const (
	Episode_NEWHOPE Episode = 0
	Episode_EMPIRE  Episode = 1
	Episode_JEDI    Episode = 2
)

// Enum value maps for Episode.
var (
	Episode_name = map[int32]string{
		0: "NEWHOPE",
		1: "EMPIRE",
		2: "JEDI",
	}
	Episode_value = map[string]int32{
		"NEWHOPE": 0,
		"EMPIRE":  1,
		"JEDI":    2,
	}
)

func (x Episode) Enum() *Episode {
	p := new(Episode)
	*p = x
	return p
}

func (x Episode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Episode) Descriptor() protoreflect.EnumDescriptor {
	return file_testdata_starwars_proto_enumTypes[0].Descriptor()
}

func (Episode) Type() protoreflect.EnumType {
	return &file_testdata_starwars_proto_enumTypes[0]
}

func (x Episode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Episode.Descriptor instead.
func (Episode) EnumDescriptor() ([]byte, []int) {
	return file_testdata_starwars_proto_rawDescGZIP(), []int{0}
}

type Species int32

const (
	Species_HUMAN Species = 0
	Species_DROID Species = 1
)

// Enum value maps for Species.
var (
	Species_name = map[int32]string{
		0: "HUMAN",
		1: "DROID",
	}
	Species_value = map[string]int32{
		"HUMAN": 0,
		"DROID": 1,
	}
)

func (x Species) Enum() *Species {
	p := new(Species)
	*p = x
	return p
}

func (x Species) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Species) Descriptor() protoreflect.EnumDescriptor {
	return file_testdata_starwars_proto_enumTypes[1].Descriptor()
}

func (Species) Type() protoreflect.EnumType {
	return &file_testdata_starwars_proto_enumTypes[1]
}

func (x Species) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Species.Descriptor instead.
func (Species) EnumDescriptor() ([]byte, []int) {
	return file_testdata_starwars_proto_rawDescGZIP(), []int{1}
}

type LengthUnit int32

const (
	LengthUnit_METER LengthUnit = 0
	LengthUnit_FOOT  LengthUnit = 1
)

// Enum value maps for LengthUnit.
var (
	LengthUnit_name = map[int32]string{
		0: "METER",
		1: "FOOT",
	}
	LengthUnit_value = map[string]int32{
		"METER": 0,
		"FOOT":  1,
	}
)

func (x LengthUnit) Enum() *LengthUnit {
	p := new(LengthUnit)
	*p = x
	return p
}

func (x LengthUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LengthUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_testdata_starwars_proto_enumTypes[2].Descriptor()
}

func (LengthUnit) Type() protoreflect.EnumType {
	return &file_testdata_starwars_proto_enumTypes[2]
}

func (x LengthUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LengthUnit.Descriptor instead.
func (LengthUnit) EnumDescriptor() ([]byte, []int) {
	return file_testdata_starwars_proto_rawDescGZIP(), []int{2}
}

type Character struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Friends   []*Character `protobuf:"bytes,3,rep,name=friends,proto3" json:"friends,omitempty"`
	AppearsIn []Episode    `protobuf:"varint,4,rep,packed,name=appearsIn,proto3,enum=starwars.Episode" json:"appearsIn,omitempty"`
	Species   Species      `protobuf:"varint,5,opt,name=species,proto3,enum=starwars.Species" json:"species,omitempty"`
}

func (x *Character) Reset() {
	*x = Character{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_starwars_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_starwars_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_testdata_starwars_proto_rawDescGZIP(), []int{0}
}

func (x *Character) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetFriends() []*Character {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *Character) GetAppearsIn() []Episode {
	if x != nil {
		return x.AppearsIn
	}
	return nil
}

func (x *Character) GetSpecies() Species {
	if x != nil {
		return x.Species
	}
	return Species_HUMAN
}

// We can't extend Character, cuz Proto Buffers don't support class inheritance
type Human struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Character  *Character    `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	HomePlanet string        `protobuf:"bytes,2,opt,name=homePlanet,proto3" json:"homePlanet,omitempty"`
	Height     *Human_Height `protobuf:"bytes,3,opt,name=height,proto3" json:"height,omitempty"`
	Mass       float32       `protobuf:"fixed32,4,opt,name=mass,proto3" json:"mass,omitempty"`
	Starship   []*Starship   `protobuf:"bytes,5,rep,name=starship,proto3" json:"starship,omitempty"`
}

func (x *Human) Reset() {
	*x = Human{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_starwars_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Human) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Human) ProtoMessage() {}

func (x *Human) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_starwars_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Human.ProtoReflect.Descriptor instead.
func (*Human) Descriptor() ([]byte, []int) {
	return file_testdata_starwars_proto_rawDescGZIP(), []int{1}
}

func (x *Human) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

func (x *Human) GetHomePlanet() string {
	if x != nil {
		return x.HomePlanet
	}
	return ""
}

func (x *Human) GetHeight() *Human_Height {
	if x != nil {
		return x.Height
	}
	return nil
}

func (x *Human) GetMass() float32 {
	if x != nil {
		return x.Mass
	}
	return 0
}

func (x *Human) GetStarship() []*Starship {
	if x != nil {
		return x.Starship
	}
	return nil
}

type Droid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Character       *Character `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	PrimaryFunction string     `protobuf:"bytes,2,opt,name=primaryFunction,proto3" json:"primaryFunction,omitempty"`
}

func (x *Droid) Reset() {
	*x = Droid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_starwars_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Droid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Droid) ProtoMessage() {}

func (x *Droid) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_starwars_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Droid.ProtoReflect.Descriptor instead.
func (*Droid) Descriptor() ([]byte, []int) {
	return file_testdata_starwars_proto_rawDescGZIP(), []int{2}
}

func (x *Droid) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

func (x *Droid) GetPrimaryFunction() string {
	if x != nil {
		return x.PrimaryFunction
	}
	return ""
}

type FriendsConnection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCount uint32         `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Edges      []*FriendsEdge `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	Friends    []*Character   `protobuf:"bytes,3,rep,name=friends,proto3" json:"friends,omitempty"`
	Pageinfo   *PageInfo      `protobuf:"bytes,4,opt,name=pageinfo,proto3" json:"pageinfo,omitempty"`
}

func (x *FriendsConnection) Reset() {
	*x = FriendsConnection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_starwars_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendsConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendsConnection) ProtoMessage() {}

func (x *FriendsConnection) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_starwars_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendsConnection.ProtoReflect.Descriptor instead.
func (*FriendsConnection) Descriptor() ([]byte, []int) {
	return file_testdata_starwars_proto_rawDescGZIP(), []int{3}
}

func (x *FriendsConnection) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *FriendsConnection) GetEdges() []*FriendsEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *FriendsConnection) GetFriends() []*Character {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *FriendsConnection) GetPageinfo() *PageInfo {
	if x != nil {
		return x.Pageinfo
	}
	return nil
}

type FriendsEdge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cursor uint32     `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Node   *Character `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *FriendsEdge) Reset() {
	*x = FriendsEdge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_starwars_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendsEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendsEdge) ProtoMessage() {}

func (x *FriendsEdge) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_starwars_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendsEdge.ProtoReflect.Descriptor instead.
func (*FriendsEdge) Descriptor() ([]byte, []int) {
	return file_testdata_starwars_proto_rawDescGZIP(), []int{4}
}

func (x *FriendsEdge) GetCursor() uint32 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *FriendsEdge) GetNode() *Character {
	if x != nil {
		return x.Node
	}
	return nil
}

type PageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartCursor uint32 `protobuf:"varint,1,opt,name=startCursor,proto3" json:"startCursor,omitempty"`
	EndCursor   uint32 `protobuf:"varint,2,opt,name=endCursor,proto3" json:"endCursor,omitempty"`
	HasNextPage bool   `protobuf:"varint,3,opt,name=hasNextPage,proto3" json:"hasNextPage,omitempty"`
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_starwars_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_starwars_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_testdata_starwars_proto_rawDescGZIP(), []int{5}
}

func (x *PageInfo) GetStartCursor() uint32 {
	if x != nil {
		return x.StartCursor
	}
	return 0
}

func (x *PageInfo) GetEndCursor() uint32 {
	if x != nil {
		return x.EndCursor
	}
	return 0
}

func (x *PageInfo) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

type Review struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Episode    Episode `protobuf:"varint,1,opt,name=episode,proto3,enum=starwars.Episode" json:"episode,omitempty"`
	Stars      uint32  `protobuf:"varint,2,opt,name=stars,proto3" json:"stars,omitempty"`
	Commentary string  `protobuf:"bytes,3,opt,name=commentary,proto3" json:"commentary,omitempty"`
}

func (x *Review) Reset() {
	*x = Review{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_starwars_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_starwars_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_testdata_starwars_proto_rawDescGZIP(), []int{6}
}

func (x *Review) GetEpisode() Episode {
	if x != nil {
		return x.Episode
	}
	return Episode_NEWHOPE
}

func (x *Review) GetStars() uint32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *Review) GetCommentary() string {
	if x != nil {
		return x.Commentary
	}
	return ""
}

type ReviewInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stars           uint32       `protobuf:"varint,1,opt,name=stars,proto3" json:"stars,omitempty"`
	Commentary      string       `protobuf:"bytes,2,opt,name=commentary,proto3" json:"commentary,omitempty"`
	FavouriteColour *ColourInput `protobuf:"bytes,3,opt,name=favouriteColour,proto3" json:"favouriteColour,omitempty"`
}

func (x *ReviewInput) Reset() {
	*x = ReviewInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_starwars_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReviewInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewInput) ProtoMessage() {}

func (x *ReviewInput) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_starwars_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewInput.ProtoReflect.Descriptor instead.
func (*ReviewInput) Descriptor() ([]byte, []int) {
	return file_testdata_starwars_proto_rawDescGZIP(), []int{7}
}

func (x *ReviewInput) GetStars() uint32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *ReviewInput) GetCommentary() string {
	if x != nil {
		return x.Commentary
	}
	return ""
}

func (x *ReviewInput) GetFavouriteColour() *ColourInput {
	if x != nil {
		return x.FavouriteColour
	}
	return nil
}

type ColourInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Red   uint32 `protobuf:"varint,1,opt,name=red,proto3" json:"red,omitempty"`
	Green uint32 `protobuf:"varint,2,opt,name=green,proto3" json:"green,omitempty"`
	Blue  uint32 `protobuf:"varint,3,opt,name=blue,proto3" json:"blue,omitempty"`
}

func (x *ColourInput) Reset() {
	*x = ColourInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_starwars_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColourInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColourInput) ProtoMessage() {}

func (x *ColourInput) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_starwars_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColourInput.ProtoReflect.Descriptor instead.
func (*ColourInput) Descriptor() ([]byte, []int) {
	return file_testdata_starwars_proto_rawDescGZIP(), []int{8}
}

func (x *ColourInput) GetRed() uint32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *ColourInput) GetGreen() uint32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *ColourInput) GetBlue() uint32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

type Starship struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Length      *Starship_Length `protobuf:"bytes,3,opt,name=length,proto3" json:"length,omitempty"`
	Coordinates []*Starship_Row  `protobuf:"bytes,4,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
}

func (x *Starship) Reset() {
	*x = Starship{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_starwars_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Starship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Starship) ProtoMessage() {}

func (x *Starship) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_starwars_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Starship.ProtoReflect.Descriptor instead.
func (*Starship) Descriptor() ([]byte, []int) {
	return file_testdata_starwars_proto_rawDescGZIP(), []int{9}
}

func (x *Starship) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Starship) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Starship) GetLength() *Starship_Length {
	if x != nil {
		return x.Length
	}
	return nil
}

func (x *Starship) GetCoordinates() []*Starship_Row {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type Human_Height struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unit  LengthUnit `protobuf:"varint,1,opt,name=unit,proto3,enum=starwars.LengthUnit" json:"unit,omitempty"`
	Value float32    `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Human_Height) Reset() {
	*x = Human_Height{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_starwars_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Human_Height) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Human_Height) ProtoMessage() {}

func (x *Human_Height) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_starwars_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Human_Height.ProtoReflect.Descriptor instead.
func (*Human_Height) Descriptor() ([]byte, []int) {
	return file_testdata_starwars_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Human_Height) GetUnit() LengthUnit {
	if x != nil {
		return x.Unit
	}
	return LengthUnit_METER
}

func (x *Human_Height) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Starship_Length struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unit  LengthUnit `protobuf:"varint,1,opt,name=unit,proto3,enum=starwars.LengthUnit" json:"unit,omitempty"`
	Value float32    `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Starship_Length) Reset() {
	*x = Starship_Length{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_starwars_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Starship_Length) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Starship_Length) ProtoMessage() {}

func (x *Starship_Length) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_starwars_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Starship_Length.ProtoReflect.Descriptor instead.
func (*Starship_Length) Descriptor() ([]byte, []int) {
	return file_testdata_starwars_proto_rawDescGZIP(), []int{9, 0}
}

func (x *Starship_Length) GetUnit() LengthUnit {
	if x != nil {
		return x.Unit
	}
	return LengthUnit_METER
}

func (x *Starship_Length) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Starship_Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []float32 `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *Starship_Row) Reset() {
	*x = Starship_Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_starwars_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Starship_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Starship_Row) ProtoMessage() {}

func (x *Starship_Row) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_starwars_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Starship_Row.ProtoReflect.Descriptor instead.
func (*Starship_Row) Descriptor() ([]byte, []int) {
	return file_testdata_starwars_proto_rawDescGZIP(), []int{9, 1}
}

func (x *Starship_Row) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_testdata_starwars_proto protoreflect.FileDescriptor

var file_testdata_starwars_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x73, 0x74, 0x61, 0x72, 0x77,
	0x61, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x74, 0x61, 0x72, 0x77,
	0x61, 0x72, 0x73, 0x22, 0xbc, 0x01, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72,
	0x73, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x07, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x73, 0x12, 0x2f, 0x0a, 0x09, 0x61, 0x70, 0x70, 0x65, 0x61, 0x72, 0x73, 0x49,
	0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61,
	0x72, 0x73, 0x2e, 0x45, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x61, 0x70, 0x70, 0x65,
	0x61, 0x72, 0x73, 0x49, 0x6e, 0x12, 0x2b, 0x0a, 0x07, 0x73, 0x70, 0x65, 0x63, 0x69, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72,
	0x73, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x65, 0x73, 0x52, 0x07, 0x73, 0x70, 0x65, 0x63, 0x69,
	0x65, 0x73, 0x22, 0x98, 0x02, 0x0a, 0x05, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x12, 0x31, 0x0a, 0x09,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x12,
	0x1e, 0x0a, 0x0a, 0x68, 0x6f, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x6f, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x12,
	0x2e, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e,
	0x2e, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x61, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6d,
	0x61, 0x73, 0x73, 0x12, 0x2e, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x73, 0x68, 0x69, 0x70, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x08, 0x73, 0x74, 0x61, 0x72, 0x73,
	0x68, 0x69, 0x70, 0x1a, 0x48, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x28, 0x0a,
	0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x73, 0x74,
	0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x55, 0x6e, 0x69,
	0x74, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x64, 0x0a,
	0x05, 0x44, 0x72, 0x6f, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x74, 0x61, 0x72,
	0x77, 0x61, 0x72, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x09,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x0f, 0x70, 0x72, 0x69,
	0x6d, 0x61, 0x72, 0x79, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0xbf, 0x01, 0x0a, 0x11, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x64, 0x67,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77,
	0x61, 0x72, 0x73, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x45, 0x64, 0x67, 0x65, 0x52,
	0x05, 0x65, 0x64, 0x67, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61,
	0x72, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x07, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61,
	0x72, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x4e, 0x0a, 0x0b, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73,
	0x45, 0x64, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x27, 0x0a, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x74, 0x61,
	0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52,
	0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x6c, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x43, 0x75, 0x72,
	0x73, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x43, 0x75, 0x72, 0x73, 0x6f,
	0x72, 0x12, 0x20, 0x0a, 0x0b, 0x68, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74, 0x50,
	0x61, 0x67, 0x65, 0x22, 0x6b, 0x0a, 0x06, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x2b, 0x0a,
	0x07, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11,
	0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x45, 0x70, 0x69, 0x73, 0x6f, 0x64,
	0x65, 0x52, 0x07, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x79,
	0x22, 0x84, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x61, 0x72, 0x79, 0x12, 0x3f, 0x0a, 0x0f, 0x66, 0x61, 0x76, 0x6f, 0x75, 0x72,
	0x69, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x75,
	0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x0f, 0x66, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74,
	0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x22, 0x49, 0x0a, 0x0b, 0x43, 0x6f, 0x6c, 0x6f, 0x75,
	0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x65, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x67, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x62, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x62, 0x6c,
	0x75, 0x65, 0x22, 0x84, 0x02, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x53,
	0x74, 0x61, 0x72, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x52, 0x06,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x38, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x74,
	0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x73, 0x68, 0x69, 0x70, 0x2e,
	0x52, 0x6f, 0x77, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73,
	0x1a, 0x48, 0x0a, 0x06, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x28, 0x0a, 0x04, 0x75, 0x6e,
	0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77,
	0x61, 0x72, 0x73, 0x2e, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x04,
	0x75, 0x6e, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x1d, 0x0a, 0x03, 0x52, 0x6f,
	0x77, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x02, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x2a, 0x2c, 0x0a, 0x07, 0x45, 0x70, 0x69,
	0x73, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x45, 0x57, 0x48, 0x4f, 0x50, 0x45, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x4d, 0x50, 0x49, 0x52, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x4a, 0x45, 0x44, 0x49, 0x10, 0x02, 0x2a, 0x1f, 0x0a, 0x07, 0x53, 0x70, 0x65, 0x63, 0x69,
	0x65, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x55, 0x4d, 0x41, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x44, 0x52, 0x4f, 0x49, 0x44, 0x10, 0x01, 0x2a, 0x21, 0x0a, 0x0a, 0x4c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x45, 0x54, 0x45, 0x52, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x4f, 0x4f, 0x54, 0x10, 0x01, 0x42, 0x2b, 0x5a, 0x29, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6f, 0x66,
	0x67, 0x6f, 0x64, 0x39, 0x34, 0x2f, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x74, 0x61, 0x69, 0x6c, 0x2f,
	0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testdata_starwars_proto_rawDescOnce sync.Once
	file_testdata_starwars_proto_rawDescData = file_testdata_starwars_proto_rawDesc
)

func file_testdata_starwars_proto_rawDescGZIP() []byte {
	file_testdata_starwars_proto_rawDescOnce.Do(func() {
		file_testdata_starwars_proto_rawDescData = protoimpl.X.CompressGZIP(file_testdata_starwars_proto_rawDescData)
	})
	return file_testdata_starwars_proto_rawDescData
}

var file_testdata_starwars_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_testdata_starwars_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_testdata_starwars_proto_goTypes = []interface{}{
	(Episode)(0),              // 0: starwars.Episode
	(Species)(0),              // 1: starwars.Species
	(LengthUnit)(0),           // 2: starwars.LengthUnit
	(*Character)(nil),         // 3: starwars.Character
	(*Human)(nil),             // 4: starwars.Human
	(*Droid)(nil),             // 5: starwars.Droid
	(*FriendsConnection)(nil), // 6: starwars.FriendsConnection
	(*FriendsEdge)(nil),       // 7: starwars.FriendsEdge
	(*PageInfo)(nil),          // 8: starwars.PageInfo
	(*Review)(nil),            // 9: starwars.Review
	(*ReviewInput)(nil),       // 10: starwars.ReviewInput
	(*ColourInput)(nil),       // 11: starwars.ColourInput
	(*Starship)(nil),          // 12: starwars.Starship
	(*Human_Height)(nil),      // 13: starwars.Human.Height
	(*Starship_Length)(nil),   // 14: starwars.Starship.Length
	(*Starship_Row)(nil),      // 15: starwars.Starship.Row
}
var file_testdata_starwars_proto_depIdxs = []int32{
	3,  // 0: starwars.Character.friends:type_name -> starwars.Character
	0,  // 1: starwars.Character.appearsIn:type_name -> starwars.Episode
	1,  // 2: starwars.Character.species:type_name -> starwars.Species
	3,  // 3: starwars.Human.character:type_name -> starwars.Character
	13, // 4: starwars.Human.height:type_name -> starwars.Human.Height
	12, // 5: starwars.Human.starship:type_name -> starwars.Starship
	3,  // 6: starwars.Droid.character:type_name -> starwars.Character
	7,  // 7: starwars.FriendsConnection.edges:type_name -> starwars.FriendsEdge
	3,  // 8: starwars.FriendsConnection.friends:type_name -> starwars.Character
	8,  // 9: starwars.FriendsConnection.pageinfo:type_name -> starwars.PageInfo
	3,  // 10: starwars.FriendsEdge.node:type_name -> starwars.Character
	0,  // 11: starwars.Review.episode:type_name -> starwars.Episode
	11, // 12: starwars.ReviewInput.favouriteColour:type_name -> starwars.ColourInput
	14, // 13: starwars.Starship.length:type_name -> starwars.Starship.Length
	15, // 14: starwars.Starship.coordinates:type_name -> starwars.Starship.Row
	2,  // 15: starwars.Human.Height.unit:type_name -> starwars.LengthUnit
	2,  // 16: starwars.Starship.Length.unit:type_name -> starwars.LengthUnit
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_testdata_starwars_proto_init() }
func file_testdata_starwars_proto_init() {
	if File_testdata_starwars_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testdata_starwars_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Character); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_starwars_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Human); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_starwars_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Droid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_starwars_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendsConnection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_starwars_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendsEdge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_starwars_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_starwars_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Review); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_starwars_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReviewInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_starwars_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColourInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_starwars_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Starship); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_starwars_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Human_Height); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_starwars_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Starship_Length); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_starwars_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Starship_Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testdata_starwars_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_starwars_proto_goTypes,
		DependencyIndexes: file_testdata_starwars_proto_depIdxs,
		EnumInfos:         file_testdata_starwars_proto_enumTypes,
		MessageInfos:      file_testdata_starwars_proto_msgTypes,
	}.Build()
	File_testdata_starwars_proto = out.File
	file_testdata_starwars_proto_rawDesc = nil
	file_testdata_starwars_proto_goTypes = nil
	file_testdata_starwars_proto_depIdxs = nil
}
